// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.zpb.dubbo.proto.hello;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.zpb.dubbo.proto.hello.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
