// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.zpb.dubbo.proto.hello;

public final class Hello {
  private Hello() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zpb_dubbo_proto_hello_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zpb_dubbo_proto_hello_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zpb_dubbo_proto_hello_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zpb_dubbo_proto_hello_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013hello.proto\022\031com.zpb.dubbo.proto.hello" +
      "\"\034\n\014HelloRequest\022\014\n\004name\030\001 \001(\t\" \n\rHelloR" +
      "esponse\022\017\n\007message\030\002 \001(\t2m\n\014HelloService" +
      "\022]\n\010sayHello\022\'.com.zpb.dubbo.proto.hello" +
      ".HelloRequest\032(.com.zpb.dubbo.proto.hell" +
      "o.HelloResponseB\005P\001\240\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_zpb_dubbo_proto_hello_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_zpb_dubbo_proto_hello_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zpb_dubbo_proto_hello_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_zpb_dubbo_proto_hello_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_zpb_dubbo_proto_hello_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zpb_dubbo_proto_hello_HelloResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
