spring:
  application:
    name: apache-dubbo-service
server:
  port: 9000
#
#dubbo:
#  application:
#    name: ${spring.application.name}
#    qos-enable: true
#    qos-port: 33333
#    qos-accept-foreign-ip: false
#
#  # 注册中心地址
#  registry:
#    address: nacos://127.0.0.1:8848
  # 协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受
#  protocol:
#    port: 20881
#    name: dubbo
#    serialization: protobuf

