// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TripleDemo.proto

package com.zpb.dubbo.proto.triple;

public interface TripleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.zpb.dubbo.proto.triple.TripleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
