// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TripleDemo.proto

package com.zpb.dubbo.proto.triple;

public interface TripleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.zpb.dubbo.proto.triple.TripleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
