// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TripleDemo.proto

package com.zpb.dubbo.proto.triple;

public final class TripleDemo {
  private TripleDemo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zpb_dubbo_proto_triple_TripleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zpb_dubbo_proto_triple_TripleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zpb_dubbo_proto_triple_TripleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zpb_dubbo_proto_triple_TripleResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020TripleDemo.proto\022\032com.zpb.dubbo.proto." +
      "triple\"\035\n\rTripleRequest\022\014\n\004name\030\001 \001(\t\"!\n" +
      "\016TripleResponse\022\017\n\007message\030\002 \001(\t2r\n\rTrip" +
      "leService\022a\n\010sayHello\022).com.zpb.dubbo.pr" +
      "oto.triple.TripleRequest\032*.com.zpb.dubbo" +
      ".proto.triple.TripleResponseB\005P\001\240\001\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_zpb_dubbo_proto_triple_TripleRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_zpb_dubbo_proto_triple_TripleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zpb_dubbo_proto_triple_TripleRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_zpb_dubbo_proto_triple_TripleResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_zpb_dubbo_proto_triple_TripleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zpb_dubbo_proto_triple_TripleResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
